<a href="https://colab.research.google.com/github/MayankSangwan07/ML_ASSIGNMENTS/blob/main/ML_A01_MAYANK_SANGWAN_102316070.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**QUES 1**

In [ ]:
import numpy as np

In [ ]:
# (a) Reverse the NumPy array
arr = np.array([1,2,3,6,4,5])

print("Orginal Array : ",arr)
rev_arr = arr[::-1]
print("Reverse : ", rev_arr)

Orginal Array :  [1 2 3 6 4 5]
Reverse :  [5 4 6 3 2 1]


In [ ]:
# (b) Flatten using two methods
arr = np.array([[1,2,3],[2,4,5],[1,2,3]])
flat1 = arr.flatten()
flat2 = arr.ravel()
print("flaten - method 1 : ",flat1)
print("flaten - method 2 : ",flat2)

flaten - method 1 :  [1 2 3 2 4 5 1 2 3]
flaten - method 2 :  [1 2 3 2 4 5 1 2 3]


In [ ]:
# (c) Compare arrays
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
print("Array equal? :",np.array_equal(arr1,arr2))

Array equal? : True


In [ ]:
# (d) Most frequent value and indices
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])

def most_freq(arr):
  vals,counts = np.unique(arr,return_counts=True)
  max_count = np.max(counts)
  most_val = vals[counts == max_count]
  indices = [np.where(arr == v)[0] for v in most_val]
  return most_val, indices

print("Most frequent value in x : ",most_freq(x))
print("Most frequent value in y : ",most_freq(y))

Most frequent value in x :  (array([1]), [array([0, 5, 7, 8, 9])])
Most frequent value in y :  (array([1, 3]), [array([0, 1, 2]), array([4, 8, 9])])


In [ ]:
# (e) Matrix sums
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Total sum:",gfg.sum())
print("Row-wise sum:",np.sum(gfg,axis=1))
print("Column-wise sum:",np.sum(gfg,axis=0))

Total sum: 45
Row-wise sum: [[14]
 [16]
 [15]]
Column-wise sum: [[20  9 16]]


In [ ]:
# (f) Matrix operations
n_array = np.array([[55,25,15],[30,44,2],[11,45,77]])
print("Diagonal sum: ",np.trace(n_array))
eig_vals,eig_vecs = np.linalg.eig(n_array)
print("Eigen values: ",eig_vals)
print("Eigen vectors: ",eig_vecs)

print("Inverse: ",np.linalg.inv(n_array))
print("Determinant: ",np.linalg.det(n_array))

Diagonal sum:  176
Eigen values:  [98.16835147 28.097044   49.73460452]
Eigen vectors:  [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse:  [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant:  137180.0000000001


In [ ]:
# (g) Matrix multiplication & covariance
p1 = np.array([[1,2],[2,3]])
q1 = np.array([[4,5],[6,7]])
print("Mat Mul: ",np.dot(p1,q1))
print("Covariance: ",np.cov(p1,q1))

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
print("Mat Mul: ",np.dot(p2,q2))
print("Covariance: ",np.cov(p2.T,q2))

Mat Mul:  [[16 19]
 [26 31]]
Covariance:  [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
Mat Mul:  [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance:  [[ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [-2.66666667 -2.66666667  4.33333333  5.5       ]
 [-3.5        -3.5         5.5         7.        ]]


In [ ]:
# (h) Inner, outer, cartesian product
x = np.array([[2,3,4], [3,2,9]])
y = np.array([[1,5,0], [5,10,3]])

print("Inner Product: ",np.inner(x,y))
print("Outer Product: ",np.inner(x,y))
print("Cartesian Product: ",np.array(np.meshgrid(x,y)))

Inner Product:  [[17 52]
 [13 62]]
Outer Product:  [[17 52]
 [13 62]]
Cartesian Product:  [[[ 2  3  4  3  2  9]
  [ 2  3  4  3  2  9]
  [ 2  3  4  3  2  9]
  [ 2  3  4  3  2  9]
  [ 2  3  4  3  2  9]
  [ 2  3  4  3  2  9]]

 [[ 1  1  1  1  1  1]
  [ 5  5  5  5  5  5]
  [ 0  0  0  0  0  0]
  [ 5  5  5  5  5  5]
  [10 10 10 10 10 10]
  [ 3  3  3  3  3  3]]]


**QUES 2**

In [ ]:
# (a) Array operations

array = np.array([[1,-2,3],[-4,5,-6]])
print("Absolute value: ",np.abs(array))

flat = array.flatten()
print("percentiles(flat): ",np.percentile(flat,[25,50,75]))
print("precentiles(col): ",np.percentile(array,[25,50,75],axis=0))
print("precentiles(row): ",np.percentile(array,[25,50,75],axis=1))


print("Mean(flat): ",np.mean(flat))
print("Median(flat): ",np.median(flat))
print("Std Dev(flat): ",np.std(flat))
print("Mean(col): ",np.mean(flat,axis=0))
print("Median(col): ",np.median(flat,axis=0))
print("Std Dev(col): ",np.std(flat,axis=0))
print("Mean(row): ",np.mean(array,axis=1))
print("Median(row): ",np.median(array,axis=1))
print("Std Dev(row): ",np.std(array,axis=1))

Absolute value:  [[1 2 3]
 [4 5 6]]
percentiles(flat):  [-3.5 -0.5  2.5]
precentiles(col):  [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
precentiles(row):  [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean(flat):  -0.5
Median(flat):  -0.5
Std Dev(flat):  3.8622100754188224
Mean(col):  -0.5
Median(col):  -0.5
Std Dev(col):  3.8622100754188224
Mean(row):  [ 0.66666667 -1.66666667]
Median(row):  [ 1. -4.]
Std Dev(row):  [2.05480467 4.78423336]


In [ ]:
# (b) Floor, ceil, trunc, round
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

print("Floor: ",np.floor(a))
print("Ceil: ",np.ceil(a))
print("Trunc: ",np.trunc(a))
print("Round: ",np.round(a))

Floor:  [-2. -2. -1.  0.  1.  1.  3.]
Ceil:  [-1. -1. -0.  1.  2.  2.  3.]
Trunc:  [-1. -1. -0.  0.  1.  1.  3.]
Round:  [-2. -2. -0.  0.  2.  2.  3.]


**QUES 3**

In [ ]:
# (a)
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("Sorted: ",np.sort(array))
print("Indices of sorted:",np.argsort(array))
print("4 smallest: ",np.sort(array)[:4])
print("5 largest: ",np.sort(array)[-5:])

Sorted:  [ 10  16  16  52  54  62 453]
Indices of sorted: [0 3 4 1 5 2 6]
4 smallest:  [10 16 16 52]
5 largest:  [ 16  52  54  62 453]


In [ ]:
# (b)
array2 = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
ints = array2[array2 == array2.astype(int)]
floats = array2[array2 != array2.astype(int)]
print("Integers only: ", ints)
print("Floats only: ", floats)

Integers only:  [1. 2. 3. 2.]
Floats only:  [1.2 2.2]


**QUES 4**

In [ ]:
from PIL import Image

In [ ]:
# (a) Function to read image and save as text

def img_to_array(path):
  img = Image.open(path)
  img_array = np.array(img)
  if len(img_array.shape) == 3: #RGB
    np.savetxt("image_rgb.txt",img_array.reshape(-1,img_array.shape[-1]),fmt='%d')
    print("Saved RGB image array to iamge_rgb.txt")
  else: #Grayscale
    np.savetxt("image_gray.txt",img_Array,fmt='%d')
    print("Saved Grayscale image array to image_gray.txt")

# img_to_array("myimage.txt")

In [ ]:
# (b) Load saved file
def load_saved_txt(filename):
  data = np.loadtxt(filename,dtype=int)
  print("Loaded data shape:",data.shape)
  return data

# data = load_saved_txt("image_rgb.txt")